import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { parseDraw } from '../supabase/functions/_shared/svenska-spel.mjs';
import { draw } from './fixtures/draw.mjs';

let db;
const uid = n => `00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const query = async (sql, args=[]) => (await db.query(sql,args)).rows;
const scalar = async (sql,args=[]) => Object.values((await query(sql,args))[0])[0];
async function asUser(n, action) {
  await db.exec('set role authenticated');
  await query("select set_config('request.jwt.claim.sub',$1,false)",[uid(n)]);
  try { return await action(); } finally { await db.exec('reset role'); }
}
let isolated = false;
async function rpc(name,args) {
  if (isolated) await db.exec('savepoint rpc_attempt');
  try {
    const result=await scalar(`select public.${name}(${args.map((_,i)=>`$${i+1}`).join(',')})`,args);
    if (isolated) await db.exec('release savepoint rpc_attempt');
    return result;
  } catch (error) {
    if (isolated) await db.exec('rollback to savepoint rpc_attempt; release savepoint rpc_attempt');
    throw error;
  }
}
let parsed;
before(async () => {
  db = new PGlite();
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create table auth.users(id uuid primary key, email text, is_anonymous boolean default true);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    create function auth.role() returns text language sql stable as $$select current_user::text$$;
    grant usage on schema public,auth to anon,authenticated,service_role;`);
  // Reconstruct the actual supplied production schema (no production data or connection).
  const schema = JSON.parse(await readFile(new URL('./fixtures/legacy-schema.json',import.meta.url),'utf8'));
  for (const table of schema.tables) {
    const columns = schema.columns.filter(c=>c.table===table.table).map(c=>
      `"${c.column}" ${c.data_type}${c.identity==='YES'?' generated by default as identity':c.default?` default ${c.default}`:''}${c.nullable==='NO'?' not null':''}`);
    await db.exec(`create table public.${table.table} (${columns.join(',')})`);
  }
  for (const constraint of schema.constraints.filter(c=>c.constraint_type!=='FOREIGN KEY'))
    await db.exec(`alter table public.${constraint.table} add constraint ${constraint.constraint_name} ${constraint.definition}`);
  for (const constraint of schema.constraints.filter(c=>c.constraint_type==='FOREIGN KEY'))
    await db.exec(`alter table public.${constraint.table} add constraint ${constraint.constraint_name} ${constraint.definition}`);
  for (const fn of schema.functions) await db.exec(fn.definition);
  for (const table of schema.tables) {
    await db.exec(`alter table public.${table.table} enable row level security; grant all on public.${table.table} to anon,authenticated`);
  }
  for (const policy of schema.rls_policies) {
    await db.exec(`create policy "${policy.policy_name}" on public.${policy.table} for ${policy.command} to ${policy.roles.join(',')}
      ${policy.using ? `using (${policy.using})` : ''} ${policy.with_check ? `with check (${policy.with_check})` : ''}`);
  }
  await db.exec(`create trigger trg_round_players_recompute after insert or update or delete on public.round_players for each row execute function public.recompute_round_total()`);
  for (const view of schema.views) await db.exec(`create view public.${view.view_name} as ${view.definition}`);
  await db.exec(`create unique index rounds_season_roundnumber_idx on rounds(season_id,roundnumber);
    insert into players(name) values ('Ompen'),('Sillen'),('Adrian'),('Danne');
    insert into seasons(name,start_year,end_year,is_current) values ('2025/26',2025,2026,false),('2026/27',2026,2027,true);
    insert into rounds(roundnumber,week,season_id) values (1,1,1);
    insert into round_players(round_id,player_id,score,matches_picked) values (1,1,3,4),(1,2,1,3),(1,3,2,3),(1,4,2,3);`);
  for (let i=1;i<=8;i++) await query('insert into auth.users(id) values($1)',[uid(i)]);
  await db.exec(await readFile(new URL('../supabase/migrations/202609160001_live_tipping.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202609160002_admin_login.sql',import.meta.url),'utf8'));
  const bootstrap = await rpc('live_bootstrap_admin',[1]);
  await asUser(1,()=>rpc('live_redeem_invite',[bootstrap]));
  for (let i=2;i<=4;i++) {
    const invitation = await asUser(1,()=>rpc('live_create_invite',[i]));
    await asUser(i,()=>rpc('live_redeem_invite',[invitation]));
  }
  const deadline = new Date(Date.now()+86400000).toISOString();
  parsed = parseDraw(draw({ regCloseTime: deadline, regOpenTime: new Date(Date.now()-3600000).toISOString() }));
  // Exercise an upgrade from the previous fixed allocation with one saved tip.
  await rpc('live_import_draw',[parsed,draw(),new Date().toISOString(),new Date(Date.now()+3600000).toISOString()]);
  await asUser(1,()=>rpc('live_configure_allocation',[1,[1,1,1,1,2,2,2,3,3,3,4,4,4]]));
  await asUser(2,()=>rpc('live_save_pick',[4971,5,'1X','104',0]));
  await db.exec(await readFile(new URL('../supabase/migrations/202609160003_free_match_choice.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202609190001_round_recap.sql',import.meta.url),'utf8'));
});
after(async () => { await db?.close(); });

test('migration preserves history and closes old RPCs/views to outsiders', async () => {
  assert.equal(await scalar('select sum(score) from round_players'),8);
  assert.equal(await scalar("select count(*) from pg_policies where schemaname='public' and policyname not in ('league_read','league_admin','recap_own_read')"),0);
  await assert.rejects(rpc('live_bootstrap_admin',[2]),/En admin finns redan/);
  await asUser(5, async () => {
    for(const table of ['players','rounds','round_players','player_stats','player_stats_by_season','live_members'])
      assert.equal((await query(`select * from ${table}`)).length,0,table);
    await assert.rejects(rpc('lock_in_picks_block_match',[4971,uid(5),'[]']),/permission denied/);
    await assert.rejects(query('update live_members set is_admin=true'),/permission denied/);
    await assert.rejects(query("insert into profiles(id,display_name,role) values($1,'evil','admin')",[uid(5)]),/permission denied/);
    await assert.rejects(rpc('live_bootstrap_admin',[5]),/permission denied/);
    await assert.rejects(query('select * from live_invites'),/permission denied/);
  });
  await db.exec('set role anon');
  await assert.rejects(query('select * from rounds'),/permission denied/);
  await db.exec('reset role');
});
test('rotation controls quota only; upgrade frees unpicked matches and preserves saved tips', async () => {
  await asUser(2,async()=>await assert.rejects(rpc('live_configure_rotation',[[1,2,3,4]]),/Endast admin/));
  await asUser(1,async()=>{
    await rpc('live_configure_rotation',[[2,1,3,4]]);
    assert.equal(await scalar('select player_id from live_rotation where position=1'),2);
    await rpc('live_configure_rotation',[[1,2,3,4]]);
    await assert.rejects(rpc('live_configure_rotation',[[1,1,3,4]]));
  });
  assert.equal(await scalar('select status from live_draws'),'open');
  assert.equal(await scalar('select count(*) from live_events where player_id is null'),12);
  assert.equal(await scalar('select player_id from live_events where event_number=5'),2);
  assert.equal(await scalar('select pick from live_picks where event_number=5'),'1X');
  assert.equal(await scalar('select assigned from live_status(4971) where player_id=1'),4);
  assert.equal(await scalar('select assigned from live_status(4971) where player_id=2'),3);
  assert.equal(await scalar("select count(*) from pg_proc where proname='live_configure_allocation'"),0);
});
test('drafts autosave; ownership, max signs, half quota and optimistic revisions enforced', async () => {
  await asUser(2,async()=>{
    await assert.rejects(rpc('live_save_pick',[4971,5,'1X2','104',0]),/Högst två/);
    await assert.rejects(rpc('live_save_pick',[4971,5,'2','104',0]),/annan enhet/);
    await rpc('live_save_pick',[4971,6,'X2','105',0]);
    await assert.rejects(rpc('live_save_pick',[4971,7,'12','106',0]),/Högst två halvgarderingar/);
    await rpc('live_save_pick',[4971,7,'2','106',0]);
    assert.equal(await scalar('select complete from live_status(4971) where player_id=2'),true);
    await assert.rejects(query("update live_picks set pick='1'"),/permission denied/);
  });
  await asUser(1,async()=>{
    for(const [event,pick] of [[1,'1X'],[2,'12'],[3,'1'],[4,'2']]) await rpc('live_save_pick',[4971,event,pick,String(99+event),0]);
    assert.equal(await scalar('select complete from live_status(4971) where player_id=1'),true);
    assert.equal(await scalar('select count(*) from live_picks'),7); // everybody sees all live picks
  });
  await asUser(3,()=>assert.rejects(rpc('live_save_pick',[4971,5,'2','104',1]),/redan tagen/));
});
test('free claims enforce exact spike/half quotas, releases, competing claims and admin quotas', async () => {
  await db.exec('begin');
  isolated = true;
  try {
    const next={...structuredClone(parsed),draw_number:6001};
    await rpc('live_import_draw',[next,{},new Date().toISOString(),new Date().toISOString()]);
    assert.equal(await scalar('select status from live_draws where draw_number=6001'),'open');
    assert.equal(await scalar('select four_player_id from live_draws where draw_number=6001'),2);
    assert.equal(await scalar('select count(*) from live_events where draw_number=6001 and player_id is null'),13);
    await asUser(3,async()=>{
      const saved=await rpc('live_save_pick',[6001,13,'1','112',0]);
      assert.equal(saved.player_id,3);
      await assert.rejects(rpc('live_save_pick',[6001,12,'X','111',0]),/Högst 1 spikar/);
      await assert.rejects(rpc('live_save_pick',[6001,12,'X','111',0,4]),/annan spelare/);
    });
    await asUser(4,()=>assert.rejects(rpc('live_save_pick',[6001,13,'2','112',0]),/redan tagen/));
    await asUser(3,async()=>{
      const released=await rpc('live_save_pick',[6001,13,'','112',1]);
      assert.equal(released.player_id,null);
      assert.equal(await scalar('select player_id from live_events where draw_number=6001 and event_number=13'),null);
    });
    await asUser(4,async()=>{
      await assert.rejects(rpc('live_save_pick',[6001,13,'2','112',0]),/annan enhet/);
      await rpc('live_save_pick',[6001,13,'2','112',2]);
    });
    await asUser(3,async()=>{
      await rpc('live_save_pick',[6001,12,'1X','111',0]);
      await rpc('live_save_pick',[6001,11,'12','110',0]);
      await assert.rejects(rpc('live_save_pick',[6001,10,'X2','109',0]),/Högst två halvgarderingar/);
      await rpc('live_save_pick',[6001,10,'X','109',0]);
      await assert.rejects(rpc('live_save_pick',[6001,9,'1','108',0]),/redan valt dina 3/);
      assert.equal(await scalar('select complete from live_status(6001) where player_id=3'),true);
    });
    await asUser(2,async()=>{
      await rpc('live_save_pick',[6001,1,'1','100',0]);
      await rpc('live_save_pick',[6001,2,'X','101',0]);
      await assert.rejects(rpc('live_save_pick',[6001,3,'2','102',0]),/Högst 2 spikar/);
      await rpc('live_save_pick',[6001,3,'1X','102',0]);
      await rpc('live_save_pick',[6001,4,'12','103',0]);
      await assert.rejects(rpc('live_save_pick',[6001,5,'1X','104',0]),/redan valt dina 4/);
      assert.equal(await scalar('select complete from live_status(6001) where player_id=2'),true);
    });
    await asUser(1,()=>assert.rejects(rpc('live_save_pick',[6001,9,'1','108',0,3]),/redan valt dina 3/));
    await rpc('live_import_draw',[next,{},new Date().toISOString(),new Date().toISOString()]);
    assert.equal(await scalar('select player_id from live_events where draw_number=6001 and event_number=13'),4);
  } finally { isolated = false; await db.exec('rollback'); }
});

test('bad refresh retains valid data; replacement clears values and pick, preserving audit and raw snapshots', async () => {
  const invalid=structuredClone(parsed); invalid.events[0].odds=null; invalid.events[0].crowd=null;
  await rpc('live_import_draw',[invalid,{ fixture:'invalid' },new Date().toISOString(),new Date().toISOString()]);
  assert.deepEqual(await scalar('select odds from live_events where event_number=1'),[1.65,4.2,5.5]);
  invalid.events[0].match_id='999'; invalid.events[0].home_team='Replacement';
  await rpc('live_import_draw',[invalid,{ fixture:'replacement' },new Date().toISOString(),new Date().toISOString()]);
  assert.equal(await scalar('select odds from live_events where event_number=1'),null);
  assert.equal(await scalar('select pick from live_picks where event_number=1'),'');
  assert.equal(await scalar('select player_id from live_events where event_number=1'),null);
  assert.equal(await scalar("select count(*) from live_pick_audit where match_id='100' and old_pick='1X'"),1);
  assert.equal(await scalar("select count(*) from live_observations where kind='draw'"),3);
  await asUser(1,async()=>await rpc('live_save_pick',[4971,1,'1X','999',2]));
});
test('deadline denies members while admin can complete missing tips; incomplete results do not settle', async () => {
  await query("update live_draws set reg_close_time=now()-interval '1 second'");
  await asUser(2,async()=>await assert.rejects(rpc('live_save_pick',[4971,5,'1','104',2]),/Du får inte/));
  await asUser(1,async()=>{
    for(const [event,pick] of [[8,'1X'],[9,'X2'],[10,'1'],[11,'12'],[12,'1X'],[13,'2']])
      await rpc('live_save_pick',[4971,event,pick,String(99+event),0,event<=10?3:4]);
  });
  const partial={events:[{event_number:1,match_id:'100',outcome:'1'}],distribution:[]};
  assert.equal(await rpc('live_import_result',[4971,partial,partial,new Date().toISOString()]),false);
  assert.equal(await scalar('select count(*) from rounds'),1);
  assert.equal(await scalar('select count(*) from live_results'),0); // archived replacement identity wins
});
test('settlement is idempotent, spike/half right and wrong, admin changes recompute same totals', async () => {
  const result={events:Array.from({length:13},(_,i)=>({event_number:i+1,match_id:i===0?'999':String(100+i),outcome:'1',home_score:1,away_score:0})),distribution:[{name:'13',winners:2,amount:null}]};
  for(let i=0;i<10;i++) assert.equal(await rpc('live_import_result',[4971,result,result,new Date().toISOString()]),true);
  assert.equal(await scalar('select count(*) from rounds'),2);
  assert.equal(await scalar('select count(*) from round_players where round_id=2'),4);
  assert.deepEqual((await query('select score from round_players where round_id=2 order by player_id')).map(r=>r.score),[3,1,2,2]);
  assert.equal(await scalar('select totalscore from rounds where id=2'),8);
  assert.equal(await scalar('select totalscore from rounds where id=1'),8);
  await asUser(1,async()=>{
    await rpc('live_save_pick',[4971,4,'1','103',1]);
    assert.equal(await scalar('select totalscore from rounds where id=2'),9);
    const rows=await query('select p.* from live_picks p join live_events e using(draw_number,event_number) where e.player_id=2');
    rows.find(r=>r.event_number===5).pick='1'; rows.find(r=>r.event_number===7).pick='12';
    await rpc('live_admin_picks',[4971,2,rows]);
    assert.equal(await scalar('select totalscore from rounds where id=2'),10);
    await rpc('live_correct_result',[4971,6,'105','2','Officiell rättelse']);
    assert.equal(await scalar('select totalscore from rounds where id=2'),11);
    assert.equal(await scalar('select home_score from live_results where event_number=6'),null);
  });
  await rpc('live_import_result',[4971,result,result,new Date().toISOString()]);
  assert.equal(await scalar('select totalscore from rounds where id=2'),11); // manual result preserved
});
test('invite is single-use, expired and unknown tokens denied, new device revokes old reads/writes', async () => {
  let token;
  await asUser(2,async()=>await assert.rejects(rpc('live_create_invite',[2]),/Endast admin/));
  token=await asUser(1,()=>rpc('live_create_invite',[2]));
  assert.match(token,/^[a-f0-9]{64}$/);
  assert.equal(await scalar('select octet_length(token_hash) from live_invites limit 1'),32);
  await asUser(5,async()=>{
    await assert.rejects(rpc('live_redeem_invite',['0'.repeat(64)]));
    assert.equal((await rpc('live_redeem_invite',[token])).player_id,2);
    assert.equal((await query('select * from live_events')).length,13);
    await assert.rejects(rpc('live_redeem_invite',[token]));
  });
  await asUser(2,async()=>{
    assert.equal((await query('select * from live_events')).length,0);
    assert.equal((await query('select * from player_stats')).length,0);
    await assert.rejects(rpc('live_save_pick',[4971,5,'1','104',3]),/Aktivt medlemskap/);
  });
  const expired=await asUser(1,()=>rpc('live_create_invite',[3]));
  await db.exec("update live_invites set expires_at=now()-interval '1 second' where player_id=3");
  await asUser(6,async()=>await assert.rejects(rpc('live_redeem_invite',[expired])));
});
test('manual refresh cooldown and global lease are enforced in database', async () => {
  const token=await rpc('live_claim_sync',[true]); assert.ok(token);
  assert.equal(await rpc('live_claim_sync',[true]),null);
  await db.exec("update live_sync_state set lease_until='-infinity'");
  assert.equal(await rpc('live_claim_sync',[true]),null);
  assert.ok(await rpc('live_claim_sync',[false]));
  await asUser(1,async()=>await assert.rejects(rpc('live_claim_sync',[false]),/permission denied/));
});

test('permanent admin login survives player-device replacement and cannot be self-assigned', async () => {
  await asUser(5,async()=>await assert.rejects(rpc('live_set_admin_login',[2,uid(5)]),/permission denied/));
  await assert.rejects(rpc('live_set_admin_login',[1,uid(1)]),/e-post/);
  await query('update auth.users set email=$1,is_anonymous=false where id=$2',['admin@example.test',uid(7)]);
  await rpc('live_set_admin_login',[1,uid(7)]);
  await asUser(1,async()=>{
    assert.equal((await rpc('live_identity',[])).is_admin,false);
    await assert.rejects(rpc('live_create_invite',[2]),/Endast admin/);
  });
  const token=await asUser(7,async()=>{
    assert.equal((await rpc('live_identity',[])).is_admin,true);
    assert.equal(await scalar('select count(*) from live_events'),13);
    return rpc('live_create_invite',[1]);
  });
  await asUser(6,async()=>{
    const identity=await rpc('live_redeem_invite',[token]);
    assert.equal(identity.player_id,1); assert.equal(identity.is_admin,false);
  });
  await asUser(1,async()=>assert.equal((await query('select * from live_events')).length,0));
  await asUser(7,async()=>{
    assert.equal((await rpc('live_identity',[])).is_admin,true);
    assert.equal(await scalar('select count(*) from live_events'),13);
    const invitation=await rpc('live_create_invite',[4]);
    await assert.rejects(rpc('live_redeem_invite',[invitation]),/annan spelare/);
  });
});

const addRecapRound = async (number, season=2, scores=[4,2,2,1]) => {
  const id=await scalar('insert into rounds(roundnumber,week,season_id) values($1,27,$2) returning id',[number,season]);
  for(let i=1;i<=4;i++) await query('insert into round_players(round_id,player_id,score,matches_picked) values($1,$2,$3,$4)',[id,i,scores[i-1],i===1?4:3]);
  return id;
};

test('recap: no complete historical results means no recap; unsettled linked draws are excluded', async () => {
  await db.exec('begin');
  try {
    await db.exec('delete from round_players');
    assert.equal(await asUser(3,()=>rpc('round_recap_pending',[])),null);
  } finally { await db.exec('rollback'); }
  await db.exec('begin');
  try {
    await db.exec("update live_draws set status='locked'");
    const payload=await asUser(3,()=>rpc('round_recap_pending',[]));
    assert.equal(payload.round_id,1); // only the old, manually registered season
    await db.exec("update live_draws set status='settled'");
    assert.notEqual((await asUser(3,()=>rpc('round_recap_pending',[]))).round_id,1);
  } finally { await db.exec('rollback'); }
});

test('recap: latest only, consistent bounded history, opening is not seen, incomplete manual round excluded', async () => {
  const r27=await addRecapRound(27);
  await query('insert into rounds(roundnumber,week,season_id) values(28,28,2)');
  const payload=await asUser(3,()=>rpc('round_recap_pending',[]));
  assert.equal(payload.round_id,r27);
  assert.ok(payload.rounds.every(r=>r.seasonId===2 && r.roundNumber<=27));
  assert.equal(payload.rounds.at(-1).totalScore,9);
  assert.equal(payload.rounds.at(-1).players.length,4);
  assert.equal(await scalar('select count(*) from round_recap_views'),0);
  assert.deepEqual(await asUser(3,()=>rpc('round_recap_pending',[])),payload);
  await query('delete from rounds where season_id=2 and roundnumber=28');
});

test('recap: acknowledgement is idempotent, passes older rounds and does not consume a newer result', async () => {
  const r27=await scalar('select id from rounds where season_id=2 and roundnumber=27');
  const r28=await addRecapRound(28,2,[0,3,3,3]);
  await asUser(3,async()=>{
    await rpc('round_recap_acknowledge',[r27]);
    const seen=await query('select * from round_recap_views order by round_id');
    assert.equal(seen.length,3); // previous season, current round 1 and round 27
    await rpc('round_recap_acknowledge',[r27]);
    assert.deepEqual(await query('select * from round_recap_views order by round_id'),seen);
    assert.equal((await rpc('round_recap_pending',[])).round_id,r28);
    await rpc('round_recap_acknowledge',[r28]);
    assert.equal(await rpc('round_recap_pending',[]),null);
  });
  await addRecapRound(26); // late backfill must not resurrect an old recap
  assert.equal(await asUser(3,()=>rpc('round_recap_pending',[])),null);
  assert.equal((await asUser(4,()=>rpc('round_recap_pending',[]))).round_id,r28);
});

test('recap: RLS isolates receipts; outsiders and forged writes cannot acknowledge another member', async () => {
  const r28=await scalar('select id from rounds where season_id=2 and roundnumber=28');
  await asUser(4,async()=>{
    assert.equal((await query('select * from round_recap_views')).length,0);
    await assert.rejects(query('insert into round_recap_views(round_id,member_id) values($1,3)',[r28]),/permission denied/);
    await assert.rejects(query('update round_recap_views set seen_at=now()'),/permission denied/);
    await assert.rejects(query('delete from round_recap_views'),/permission denied/);
    assert.equal((await query('update rounds set totalscore=13 returning id')).length,0);
    await assert.rejects(rpc('round_recap_acknowledge',[999999]),/inte färdigregistrerad/);
  });
  await asUser(2,async()=>{ // revoked device, now owned by user 5
    assert.equal(await rpc('round_recap_pending',[]),null);
    assert.equal((await query('select * from round_recap_views')).length,0);
    await assert.rejects(rpc('round_recap_acknowledge',[r28]),/Aktivt medlemskap/);
  });
  await db.exec('set role anon');
  try { await assert.rejects(rpc('round_recap_pending',[]),/permission denied/); }
  finally { await db.exec('reset role'); }
});

test('recap: seen follows stable membership across device replacement and permanent admin login', async () => {
  const r28=await scalar('select id from rounds where season_id=2 and roundnumber=28');
  await asUser(5,()=>rpc('round_recap_acknowledge',[r28]));
  const token=await asUser(7,()=>rpc('live_create_invite',[2]));
  await asUser(8,async()=>{
    await rpc('live_redeem_invite',[token]);
    assert.equal(await rpc('round_recap_pending',[]),null);
  });
  await asUser(6,()=>rpc('round_recap_acknowledge',[r28])); // admin's player device
  assert.equal(await asUser(7,()=>rpc('round_recap_pending',[])),null); // same membership
});

test('recap: season rollover uses season chronology rather than reset round numbers', async () => {
  await query("insert into seasons(id,name,start_year,end_year,is_current) values(30,'2027/28',2027,2028,false)");
  const id=await addRecapRound(1,30);
  const payload=await asUser(3,()=>rpc('round_recap_pending',[]));
  assert.equal(payload.round_id,id);
  assert.equal(payload.rounds.length,1);
  assert.equal(payload.rounds[0].seasonId,30);
  await asUser(3,()=>rpc('round_recap_acknowledge',[id]));
  assert.equal(await asUser(3,()=>rpc('round_recap_pending',[])),null);
});
