begin;

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null unique,
  start_year smallint not null,
  end_year smallint not null,
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  constraint seasons_year_range_check check (end_year = start_year + 1)
);

comment on table public.seasons is
  'Stryktipstabellens säsonger. Historiska omgångar sparas och filtreras per säsong.';

create unique index if not exists seasons_one_current_idx
  on public.seasons (is_current)
  where is_current;

insert into public.seasons (name, start_year, end_year, is_current)
values
  ('2025/26', 2025, 2026, false),
  ('2026/27', 2026, 2027, false)
on conflict (name) do update
set start_year = excluded.start_year,
    end_year = excluded.end_year;

-- Migrationen körs vid starten av 2026/27. Alla befintliga omgångar
-- tillhör 2025/26 och den nya säsongen blir den enda aktuella.
update public.seasons set is_current = false where is_current;
update public.seasons set is_current = true where name = '2026/27';

alter table public.rounds
  add column if not exists season_id bigint references public.seasons(id) on delete restrict;

update public.rounds
set season_id = (select id from public.seasons where name = '2025/26')
where season_id is null;

alter table public.rounds alter column season_id set not null;

create index if not exists rounds_season_id_idx
  on public.rounds (season_id);

create unique index if not exists rounds_season_roundnumber_idx
  on public.rounds (season_id, roundnumber);

-- Behåller spelarna mellan säsonger, men räknar poäng och snitt separat
-- för varje säsong. Klienten filtrerar vyn på is_current eller season_id.
create or replace view public.player_stats_by_season
with (security_invoker = true)
as
with stats as (
  select
    r.season_id,
    rp.player_id,
    coalesce(sum(rp.score), 0)::bigint as score,
    coalesce(sum(rp.matches_picked), 0)::bigint as total_matches,
    count(rp.round_id)::bigint as rounds_played
  from public.round_players rp
  join public.rounds r on r.id = rp.round_id
  group by r.season_id, rp.player_id
)
select
  s.id as season_id,
  s.name as season_name,
  s.start_year,
  s.end_year,
  s.is_current,
  p.id,
  p.name,
  coalesce(st.score, 0)::bigint as score,
  coalesce(st.total_matches, 0)::bigint as total_matches,
  coalesce(st.rounds_played, 0)::bigint as rounds_played,
  case
    when coalesce(st.rounds_played, 0) = 0 then 0::numeric
    else round(st.score::numeric / st.rounds_played, 2)
  end as avg_score_per_round
from public.seasons s
cross join public.players p
left join stats st
  on st.season_id = s.id
 and st.player_id = p.id;

alter table public.seasons enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'seasons'
      and policyname = 'Seasons are readable by everyone'
  ) then
    create policy "Seasons are readable by everyone"
      on public.seasons
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

grant select on public.seasons to anon, authenticated;
grant select on public.player_stats_by_season to anon, authenticated;

commit;
